
// export const countries = [
//     { icon: "🇦🇴", currency: "AOA" },
//     { icon: "🇿🇦", currency: "ZAR" },
//     { icon: "🇳🇬", currency: "NGN" },
//     { icon: "🇪🇬", currency: "EGP" },
//     { icon: "🇰🇪", currency: "KES" },
//     { icon: "🇹🇿", currency: "TZS" },
//     { icon: "🇺🇬", currency: "UGX" },
//     { icon: "🇿🇲", currency: "ZMW" },
//     { icon: "🇲🇿", currency: "MZN" },
//     { icon: "🇳🇦", currency: "NAD" },
//     { icon: "🇧🇼", currency: "BWP" },
//     { icon: "🇬🇭", currency: "GHS" },
//     { icon: "🇲🇦", currency: "MAD" },
//     { icon: "🇹🇳", currency: "TND" },
//     { icon: "🇩🇿", currency: "DZD" },
//     { icon: "🇱🇾", currency: "LYD" },
//     { icon: "🇨🇩", currency: "CDF" },
//     { icon: "🇨🇬", currency: "XAF" },
//     { icon: "🇸🇳", currency: "XOF" },
//     { icon: "🇪🇹", currency: "ETB" },
//     { icon: "🇸🇸", currency: "SSP" },
//     { icon: "🇸🇩", currency: "SDG" },
//     { icon: "🇪🇺", currency: "EUR" },
//     { icon: "🇬🇧", currency: "GBP" },
//     { icon: "🇨🇭", currency: "CHF" },
//     { icon: "🇵🇱", currency: "PLN" },
//     { icon: "🇳🇴", currency: "NOK" },
//     { icon: "🇸🇪", currency: "SEK" },
//     { icon: "🇩🇰", currency: "DKK" },
//     { icon: "🇷🇴", currency: "RON" },
//     { icon: "🇨🇿", currency: "CZK" },
//     { icon: "🇭🇺", currency: "HUF" },
//     { icon: "🇷🇺", currency: "RUB" },
//     { icon: "🇹🇷", currency: "TRY" },
//     { icon: "🇺🇦", currency: "UAH" },
//     { icon: "🇧🇾", currency: "BYN" },
//     { icon: "🇧🇬", currency: "BGN" },
//     { icon: "🇮🇸", currency: "ISK" },
//     { icon: "🇬🇪", currency: "GEL" },
//     { icon: "🇺🇸", currency: "USD" },
//     { icon: "🇨🇦", currency: "CAD" },
//     { icon: "🇧🇷", currency: "BRL" },
//     { icon: "🇲🇽", currency: "MXN" },
//     { icon: "🇦🇷", currency: "ARS" },
//     { icon: "🇨🇱", currency: "CLP" },
//     { icon: "🇨🇴", currency: "COP" },
//     { icon: "🇵🇪", currency: "PEN" },
//     { icon: "🇻🇪", currency: "VES" },
//     { icon: "🇺🇾", currency: "UYU" },
//     { icon: "🇵🇾", currency: "PYG" },
//     { icon: "🇧🇴", currency: "BOB" },
//     { icon: "🇯🇲", currency: "JMD" },
//     { icon: "🇩🇴", currency: "DOP" },
//     { icon: "🇭🇹", currency: "HTG" },
//     { icon: "🇨🇳", currency: "CNY" },
//     { icon: "🇯🇵", currency: "JPY" },
//     { icon: "🇰🇷", currency: "KRW" },
//     { icon: "🇮🇳", currency: "INR" },
//     { icon: "🇸🇦", currency: "SAR" },
//     { icon: "🇦🇪", currency: "AED" },
//     { icon: "🇶🇦", currency: "QAR" },
//     { icon: "🇮🇶", currency: "IQD" },
//     { icon: "🇮🇷", currency: "IRR" },
//     { icon: "🇱🇧", currency: "LBP" },
//     { icon: "🇮🇱", currency: "ILS" },
//     { icon: "🇵🇰", currency: "PKR" },
//     { icon: "🇧🇩", currency: "BDT" },
//     { icon: "🇹🇭", currency: "THB" },
//     { icon: "🇮🇩", currency: "IDR" },
//     { icon: "🇲🇾", currency: "MYR" },
//     { icon: "🇸🇬", currency: "SGD" },
//     { icon: "🇭🇰", currency: "HKD" },
//     { icon: "🇦🇺", currency: "AUD" },
//     { icon: "🇳🇿", currency: "NZD" },
//     { icon: "🇵🇬", currency: "PGK" },
//     { icon: "🇫🇯", currency: "FJD" },
//     { icon: "🌐", currency: "XAF" },
//     { icon: "🌐", currency: "XOF" },
//     { icon: "🌐", currency: "XPF" },
//     { icon: "🌐", currency: "XDR" },
//     { icon: "🌐", currency: "XAU" },
//     { icon: "🌐", currency: "XAG" },
//     { icon: "🌐", currency: "BTC" },
//     { icon: "🌐", currency: "ETH" }
// ]



// export const countries = [
//     { icon: "🇦🇴", currency: "AOA" },
//     { icon: "🇲🇿", currency: "MZN" },
//     { icon: "🇪🇺", currency: "EUR" },
//     { icon: "🇬🇧", currency: "GBP" },
//     { icon: "🇷🇺", currency: "RUB" },
//     { icon: "🇺🇦", currency: "UAH" },
//     { icon: "🇬🇪", currency: "GEL" },
//     { icon: "🇺🇸", currency: "USD" },
//     { icon: "🇧🇷", currency: "BRL" },
//     { icon: "🇲🇽", currency: "MXN" },
//     { icon: "🇦🇷", currency: "ARS" },
//     { icon: "🇯🇵", currency: "JPY" },
//     { icon: "🌐", currency: "XAF" },
//     { icon: "🌐", currency: "XOF" },
//     { icon: "🌐", currency: "XPF" },
//     { icon: "🌐", currency: "XDR" },
//     { icon: "🌐", currency: "XAU" },
//     { icon: "🌐", currency: "XAG" },
//     { icon: "🌐", currency: "BTC" },
//     { icon: "🌐", currency: "ETH" }
// ]


export const currencies = [
    { icon: "🇦🇴", currency: "AOA" },
    { icon: "🇺🇸", currency: "USD" },
    { icon: "🇪🇺", currency: "EUR" },
    { icon: "🇬🇧", currency: "GBP" },
    { icon: "🇧🇷", currency: "BRL" },
    { icon: "🇯🇵", currency: "JPY" },
    { icon: "🇨🇳", currency: "CNY" },
    { icon: "🇨🇦", currency: "CAD" },
    { icon: "🇦🇺", currency: "AUD" },
    { icon: "🇨🇭", currency: "CHF" },
    { icon: "🇮🇳", currency: "INR" },
    { icon: "🇷🇺", currency: "RUB" },
    { icon: "🇰🇷", currency: "KRW" },
    { icon: "🇸🇬", currency: "SGD" },
    { icon: "🇲🇽", currency: "MXN" },
    { icon: "🇿🇦", currency: "ZAR" },
    { icon: "🇸🇦", currency: "SAR" },
    { icon: "🇹🇷", currency: "TRY" },
    { icon: "🇸🇪", currency: "SEK" },
    { icon: "🇳🇴", currency: "NOK" },
    { icon: "🇩🇰", currency: "DKK" },
    { icon: "🇵🇱", currency: "PLN" },
    { icon: "🇹🇭", currency: "THB" },
    { icon: "🇦🇪", currency: "AED" },
    { icon: "🇦🇫", currency: "AFN" },
    { icon: "🇦🇱", currency: "ALL" },
    { icon: "🇦🇲", currency: "AMD" },
    { icon: "🇦🇼", currency: "AWG" },
    { icon: "🇦🇿", currency: "AZN" },
    { icon: "🇧🇦", currency: "BAM" },
    { icon: "🇧🇧", currency: "BBD" },
    { icon: "🇧🇩", currency: "BDT" },
    { icon: "🇧🇬", currency: "BGN" },
    { icon: "🇧🇭", currency: "BHD" },
    { icon: "🇧🇮", currency: "BIF" },
    { icon: "🇧🇲", currency: "BMD" },
    { icon: "🇧🇳", currency: "BND" },
    { icon: "🇧🇴", currency: "BOB" },
    { icon: "🇧🇸", currency: "BSD" },
    { icon: "🇧🇹", currency: "BTN" },
    { icon: "🇧🇼", currency: "BWP" },
    { icon: "🇧🇾", currency: "BYN" },
    { icon: "🇧🇿", currency: "BZD" },
    { icon: "🇨🇩", currency: "CDF" },
    { icon: "🇨🇱", currency: "CLP" },
    { icon: "🇨🇴", currency: "COP" },
    { icon: "🇨🇷", currency: "CRC" },
    { icon: "🇨🇺", currency: "CUP" },
    { icon: "🇨🇻", currency: "CVE" },
    { icon: "🇨🇿", currency: "CZK" },
    { icon: "🇩🇯", currency: "DJF" },
    { icon: "🇩🇴", currency: "DOP" },
    { icon: "🇩🇿", currency: "DZD" },
    { icon: "🇪🇬", currency: "EGP" },
    { icon: "🇪🇷", currency: "ERN" },
    { icon: "🇪🇹", currency: "ETB" },
    { icon: "🇫🇯", currency: "FJD" },
    { icon: "🇫🇰", currency: "FKP" },
    { icon: "🇫🇴", currency: "FOK" },
    { icon: "🇬🇪", currency: "GEL" },
    { icon: "🇬🇬", currency: "GGP" },
    { icon: "🇬🇭", currency: "GHS" },
    { icon: "🇬🇮", currency: "GIP" },
    { icon: "🇬🇲", currency: "GMD" },
    { icon: "🇬🇳", currency: "GNF" },
    { icon: "🇬🇹", currency: "GTQ" },
    { icon: "🇬🇾", currency: "GYD" },
    { icon: "🇭🇰", currency: "HKD" },
    { icon: "🇭🇳", currency: "HNL" },
    { icon: "🇭🇷", currency: "HRK" },
    { icon: "🇭🇹", currency: "HTG" },
    { icon: "🇭🇺", currency: "HUF" },
    { icon: "🇮🇩", currency: "IDR" },
    { icon: "🇮🇱", currency: "ILS" },
    { icon: "🇮🇲", currency: "IMP" },
    { icon: "🇮🇶", currency: "IQD" },
    { icon: "🇮🇷", currency: "IRR" },
    { icon: "🇮🇸", currency: "ISK" },
    { icon: "🇯🇪", currency: "JEP" },
    { icon: "🇯🇲", currency: "JMD" },
    { icon: "🇯🇴", currency: "JOD" },
    { icon: "🇰🇪", currency: "KES" },
    { icon: "🇰🇬", currency: "KGS" },
    { icon: "🇰🇭", currency: "KHR" },
    { icon: "🇰🇮", currency: "KID" },
    { icon: "🇰🇲", currency: "KMF" },
    { icon: "🇰🇼", currency: "KWD" },
    { icon: "🇰🇾", currency: "KYD" },
    { icon: "🇰🇿", currency: "KZT" },
    { icon: "🇱🇦", currency: "LAK" },
    { icon: "🇱🇧", currency: "LBP" },
    { icon: "🇱🇰", currency: "LKR" },
    { icon: "🇱🇷", currency: "LRD" },
    { icon: "🇱🇸", currency: "LSL" },
    { icon: "🇱🇾", currency: "LYD" },
    { icon: "🇲🇦", currency: "MAD" },
    { icon: "🇲🇩", currency: "MDL" },
    { icon: "🇲🇬", currency: "MGA" },
    { icon: "🇲🇰", currency: "MKD" },
    { icon: "🇲🇲", currency: "MMK" },
    { icon: "🇲🇳", currency: "MNT" },
    { icon: "🇲🇴", currency: "MOP" },
    { icon: "🇲🇷", currency: "MRU" },
    { icon: "🇲🇺", currency: "MUR" },
    { icon: "🇲🇻", currency: "MVR" },
    { icon: "🇲🇼", currency: "MWK" },
    { icon: "🇲🇾", currency: "MYR" },
    { icon: "🇲🇿", currency: "MZN" },
    { icon: "🇳🇦", currency: "NAD" },
    { icon: "🇳🇬", currency: "NGN" },
    { icon: "🇳🇮", currency: "NIO" },
    { icon: "🇳🇵", currency: "NPR" },
    { icon: "🇳🇿", currency: "NZD" },
    { icon: "🇴🇲", currency: "OMR" },
    { icon: "🇵🇦", currency: "PAB" },
    { icon: "🇵🇪", currency: "PEN" },
    { icon: "🇵🇬", currency: "PGK" },
    { icon: "🇵🇭", currency: "PHP" },
    { icon: "🇵🇰", currency: "PKR" },
    { icon: "🇵🇾", currency: "PYG" },
    { icon: "🇶🇦", currency: "QAR" },
    { icon: "🇷🇴", currency: "RON" },
    { icon: "🇷🇸", currency: "RSD" },
    { icon: "🇷🇼", currency: "RWF" },
    { icon: "🇸🇧", currency: "SBD" },
    { icon: "🇸🇨", currency: "SCR" },
    { icon: "🇸🇩", currency: "SDG" },
    { icon: "🇸🇱", currency: "SLE" },
    { icon: "🇸🇴", currency: "SOS" },
    { icon: "🇸🇷", currency: "SRD" },
    { icon: "🇸🇸", currency: "SSP" },
    { icon: "🇸🇹", currency: "STN" },
    { icon: "🇸🇾", currency: "SYP" },
    { icon: "🇸🇿", currency: "SZL" },
    { icon: "🇹🇯", currency: "TJS" },
    { icon: "🇹🇲", currency: "TMT" },
    { icon: "🇹🇳", currency: "TND" },
    { icon: "🇹🇴", currency: "TOP" },
    { icon: "🇹🇹", currency: "TTD" },
    { icon: "🇹🇻", currency: "TVD" },
    { icon: "🇹🇼", currency: "TWD" },
    { icon: "🇹🇿", currency: "TZS" },
    { icon: "🇺🇬", currency: "UGX" },
    { icon: "🇺🇦", currency: "UAH" },
    { icon: "🇺🇾", currency: "UYU" },
    { icon: "🇺🇿", currency: "UZS" },
    { icon: "🇻🇪", currency: "VES" },
    { icon: "🇻🇳", currency: "VND" },
    { icon: "🇻🇺", currency: "VUV" },
    { icon: "🇼🇸", currency: "WST" },
    { icon: "🇽🇨", currency: "XCD" },
    { icon: "🇨🇫", currency: "XAF" },
    { icon: "🇨🇮", currency: "XOF" },
    { icon: "🇵🇫", currency: "XPF" },
    { icon: "🇾🇪", currency: "YER" },
    { icon: "🇿🇲", currency: "ZMW" },
    { icon: "🇿🇼", currency: "ZWL" }
];