
// export const countries = [
//     { icon: "🇦🇴", currency: "AOA" },
//     { icon: "🇿🇦", currency: "ZAR" },
//     { icon: "🇳🇬", currency: "NGN" },
//     { icon: "🇪🇬", currency: "EGP" },
//     { icon: "🇰🇪", currency: "KES" },
//     { icon: "🇹🇿", currency: "TZS" },
//     { icon: "🇺🇬", currency: "UGX" },
//     { icon: "🇿🇲", currency: "ZMW" },
//     { icon: "🇲🇿", currency: "MZN" },
//     { icon: "🇳🇦", currency: "NAD" },
//     { icon: "🇧🇼", currency: "BWP" },
//     { icon: "🇬🇭", currency: "GHS" },
//     { icon: "🇲🇦", currency: "MAD" },
//     { icon: "🇹🇳", currency: "TND" },
//     { icon: "🇩🇿", currency: "DZD" },
//     { icon: "🇱🇾", currency: "LYD" },
//     { icon: "🇨🇩", currency: "CDF" },
//     { icon: "🇨🇬", currency: "XAF" },
//     { icon: "🇸🇳", currency: "XOF" },
//     { icon: "🇪🇹", currency: "ETB" },
//     { icon: "🇸🇸", currency: "SSP" },
//     { icon: "🇸🇩", currency: "SDG" },
//     { icon: "🇪🇺", currency: "EUR" },
//     { icon: "🇬🇧", currency: "GBP" },
//     { icon: "🇨🇭", currency: "CHF" },
//     { icon: "🇵🇱", currency: "PLN" },
//     { icon: "🇳🇴", currency: "NOK" },
//     { icon: "🇸🇪", currency: "SEK" },
//     { icon: "🇩🇰", currency: "DKK" },
//     { icon: "🇷🇴", currency: "RON" },
//     { icon: "🇨🇿", currency: "CZK" },
//     { icon: "🇭🇺", currency: "HUF" },
//     { icon: "🇷🇺", currency: "RUB" },
//     { icon: "🇹🇷", currency: "TRY" },
//     { icon: "🇺🇦", currency: "UAH" },
//     { icon: "🇧🇾", currency: "BYN" },
//     { icon: "🇧🇬", currency: "BGN" },
//     { icon: "🇮🇸", currency: "ISK" },
//     { icon: "🇬🇪", currency: "GEL" },
//     { icon: "🇺🇸", currency: "USD" },
//     { icon: "🇨🇦", currency: "CAD" },
//     { icon: "🇧🇷", currency: "BRL" },
//     { icon: "🇲🇽", currency: "MXN" },
//     { icon: "🇦🇷", currency: "ARS" },
//     { icon: "🇨🇱", currency: "CLP" },
//     { icon: "🇨🇴", currency: "COP" },
//     { icon: "🇵🇪", currency: "PEN" },
//     { icon: "🇻🇪", currency: "VES" },
//     { icon: "🇺🇾", currency: "UYU" },
//     { icon: "🇵🇾", currency: "PYG" },
//     { icon: "🇧🇴", currency: "BOB" },
//     { icon: "🇯🇲", currency: "JMD" },
//     { icon: "🇩🇴", currency: "DOP" },
//     { icon: "🇭🇹", currency: "HTG" },
//     { icon: "🇨🇳", currency: "CNY" },
//     { icon: "🇯🇵", currency: "JPY" },
//     { icon: "🇰🇷", currency: "KRW" },
//     { icon: "🇮🇳", currency: "INR" },
//     { icon: "🇸🇦", currency: "SAR" },
//     { icon: "🇦🇪", currency: "AED" },
//     { icon: "🇶🇦", currency: "QAR" },
//     { icon: "🇮🇶", currency: "IQD" },
//     { icon: "🇮🇷", currency: "IRR" },
//     { icon: "🇱🇧", currency: "LBP" },
//     { icon: "🇮🇱", currency: "ILS" },
//     { icon: "🇵🇰", currency: "PKR" },
//     { icon: "🇧🇩", currency: "BDT" },
//     { icon: "🇹🇭", currency: "THB" },
//     { icon: "🇮🇩", currency: "IDR" },
//     { icon: "🇲🇾", currency: "MYR" },
//     { icon: "🇸🇬", currency: "SGD" },
//     { icon: "🇭🇰", currency: "HKD" },
//     { icon: "🇦🇺", currency: "AUD" },
//     { icon: "🇳🇿", currency: "NZD" },
//     { icon: "🇵🇬", currency: "PGK" },
//     { icon: "🇫🇯", currency: "FJD" },
//     { icon: "🌐", currency: "XAF" },
//     { icon: "🌐", currency: "XOF" },
//     { icon: "🌐", currency: "XPF" },
//     { icon: "🌐", currency: "XDR" },
//     { icon: "🌐", currency: "XAU" },
//     { icon: "🌐", currency: "XAG" },
//     { icon: "🌐", currency: "BTC" },
//     { icon: "🌐", currency: "ETH" }
// ]



export const countries = [
    { icon: "🇦🇴", currency: "AOA" },
    { icon: "🇲🇿", currency: "MZN" },
    { icon: "🇪🇺", currency: "EUR" },
    { icon: "🇬🇧", currency: "GBP" },
    { icon: "🇷🇺", currency: "RUB" },
    { icon: "🇺🇦", currency: "UAH" },
    { icon: "🇬🇪", currency: "GEL" },
    { icon: "🇺🇸", currency: "USD" },
    { icon: "🇧🇷", currency: "BRL" },
    { icon: "🇲🇽", currency: "MXN" },
    { icon: "🇦🇷", currency: "ARS" },
    { icon: "🇯🇵", currency: "JPY" },
    { icon: "🌐", currency: "XAF" },
    { icon: "🌐", currency: "XOF" },
    { icon: "🌐", currency: "XPF" },
    { icon: "🌐", currency: "XDR" },
    { icon: "🌐", currency: "XAU" },
    { icon: "🌐", currency: "XAG" },
    { icon: "🌐", currency: "BTC" },
    { icon: "🌐", currency: "ETH" }
]